##
# (c) 2023 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Configuration Change Re-Hash on Specific branches
on:
  push:
    branches:
      - main
      - master
      - config*
      - devel*
    paths:
      - values/**/*
      - values/*

concurrency: hash-environment-awseb-v2

permissions:
  contents: write
  packages: write
  statuses: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  update-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on pull request
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0

      - name: Update Hash
        run: make update

      - name: Push change to Branch
        uses: EndBug/add-and-commit@v9
        with:
          default_actor: github_actions
          message: "chore: Update config Hash."
          add: "values/**/* .values_hash_*"
          push: true
