##
# (c) 2023 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Automatic promotion Process Detection on Pull request
on:
  pull_request:
    types:
      - opened

concurrency:
  group: hash-environment-awseb-v2
  cancel-in-progress: false

permissions:
  contents: write
  packages: write
  statuses: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  update-hash:
    if: ${{ ! startsWith(github.head_ref, 'promote-') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      # Installs Terraform
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.7.1

      - name: Treat the PR as a promotion
        run: make env/promote

      # Do Tidy on terraform Files
      - name: Terraform tidy up
        run: tofu fmt

      - name: Push change to Branch
        uses: EndBug/add-and-commit@v9
        with:
          default_actor: github_actions
          message: "chore: Treat this PR as an environment promotion."
          add: "terraform.tfvars .bluegreen_* .values_hash_*"
          push: true
