##
# (c) 2022 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Environment Plan on Pull request
on:
  pull_request:
    types:
      - synchronize
    paths:
      - values/**/*

concurrency: environment-awseb-v2

permissions:
  contents: write
  packages: write
  statuses: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  update-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0

      - name: Update Hash
        run: make update

      - name: Push change to Branch
        uses: EndBug/add-and-commit@v9
        with:
          default_actor: github_actions
          message: "chore: Update config Hash."
          add: "values/**/*"
          pull: "--rebase"
          push: true
