## 
# (c) 2022 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Environment Plan on Opened Promotion Pull request
on:
  pull_request:
    types:
      - opened
    paths-ignore:
      - '.github/workflows/**'
      - 'modules/**'
      - '.beacon'
      - '.destroy'
    branches:
      - promote-*

concurrency:
  group: environment-awseb-v2
  cancel-in-progress: false

permissions:
  contents: read
  packages: write
  statuses: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  # Job determines which label to apply
  plan:
    uses: ./.github/workflow/plan.yml
    secrets: inherit