##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Slash command on Green To Prod
on:
  repository_dispatch:
    types:
      - green-to-prod-command
      - ok-to-prod-command
      - to-prod-command
      - apply-prod-command

permissions:
  issues: write
  contents: write
  packages: read
  statuses: write
  pull-requests: write

jobs:
  force-trafic-switch:
    runs-on: ubuntu-latest
    steps:
      # Get pull request head
      - name: Get Pull Request HEAD Ref
        uses: actions/github-script@v4
        id: the_pull
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          result-encoding: string
          script: |
            const pull_request_number = '${{ github.event.client_payload.slash_command.args.named.pull_request_number }}';
            const {data: thePull} = await github.pulls.get({
              pull_number: pull_request_number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return thePull.head.ref;

      # Proceed with checkout of source with all the references (depth=0)  
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ steps.the_pull.outputs.result }}
          token: ${{ secrets.BOT_TOKEN }}

      # Installs Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.3

      # Replacement on terraform.tfvars the switch value for the env
      - name: Proceed to switch to new environment
        run: |
          green_server_version=$(head -n 1 .bluegreen_state | head -c 1)
          sed -i -e "s/deployment_enabled[ \t]*=.*/deployment_enabled = \"${green_server_version}\"/g" terraform.tfvars
          echo "green_to_prod" > .action_plan

      # Do Tidy on terraform Files
      - name: Terraform tidy up
        run: terraform fmt

      - name: Push change to branch
        run: |
          git add .
          git config --global user.name "${{ secrets.BOT_USER }}"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git commit -a -m "chore: Pushing changes promotion of green environment to prod."
          git push origin

      - name: Label entry at proper step
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            const pull_request_number = '${{ github.event.client_payload.slash_command.args.named.pull_request_number }}';
            
            github.issues.addLabels({
              issue_number: pull_request_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [ 'blue-green/promoted' ]
            });
