##
# (c) 2022 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Slash command on Cancel/Rollback
on:
  repository_dispatch:
    types:
      - cancel-command
      - rollback-command
      - reject-command
      - close-command

concurrency:
  group: environment-awseb-v2
  cancel-in-progress: false

permissions:
  issues: write
  contents: write
  packages: read
  statuses: write
  pull-requests: write

jobs:
  rollback-environment:
    runs-on: ubuntu-latest
    steps:
      # Get pull request head
      - name: Get Pull Request HEAD Ref
        uses: actions/github-script@v7
        id: the_pull
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          result-encoding: string
          script: |
            const pull_request_number = '${{ github.event.client_payload.slash_command.args.named.pull_request_number }}';
            const {data: thePull} = await github.rest.pulls.get({
              pull_number: pull_request_number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return thePull.head.ref;

      # Proceed with checkout of source with all the references (depth=0)  
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.the_pull.outputs.result }}
          token: ${{ secrets.BOT_TOKEN }}

      - name: Rollback everything
        run: |
          echo "ROLLED BACK" >> README.md

      - name: Push change to branch
        run: |
          git add .
          git config --global user.name "${{ vars.BOT_USER }}"
          git config --global user.email "${{ vars.BOT_EMAIL }}"
          git commit -a -m "chore: Pushing changes for opening new version's traffic."
          git push origin

      - name: Label entry at proper step
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            const pull_request_number = '${{ github.event.client_payload.slash_command.args.named.pull_request_number }}';

            const {data: pullLabels} = await github.rest.issues.listLabelsOnIssue({
              issue_number: pull_request_number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const labels = pullLabels.map(label => label.name);
            
            for ( aLabel of labels ) {
              if ( aLabel == 'green-to-prod' || aLabel == 'deployed' ) {
                github.rest.issues.removeLabel({
                  issue_number: pull_request_number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: aLabel
                });
              }
            }

            github.rest.issues.addLabels({
              issue_number: pull_request_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [ 'rollback' ]
            });
